#!/usr/bin/env node
'use strict';

/**
 * Copies the Coral Spectrum runtime out of node_modules and into the view
 * directory, so the packaged extension carries its own copy of the design
 * system rather than loading it from a CDN.
 *
 * Runs automatically after `npm install` and before `npm run sandbox` /
 * `npm run package`. The copied files are build output and are not committed.
 */

const fs = require('fs');
const path = require('path');

const projectRoot = path.join(__dirname, '..');
const coralDist = path.join(
  projectRoot,
  'node_modules',
  '@adobe',
  'coral-spectrum',
  'dist'
);
// Coral derives the location of its icon sprites from the URL of coral.min.js,
// expecting the layout it ships with: <root>/dist/js/coral.min.js alongside
// <root>/dist/resources. Vendoring into any other shape breaks every icon, so
// the `dist` level is preserved here deliberately.
const destination = path.join(
  projectRoot,
  'src',
  'view',
  'vendor',
  'coral',
  'dist'
);

// Only the runtime pieces. The dist directory also carries documentation,
// coverage, and playground folders that have no place in the package.
const files = [
  ['css/coral.min.css', 'css/coral.min.css'],
  ['js/coral.min.js', 'js/coral.min.js'],
  ['resources/spectrum-icons.svg', 'resources/spectrum-icons.svg'],
  ['resources/spectrum-css-icons.svg', 'resources/spectrum-css-icons.svg'],
  ['resources/spectrum-icons-color.svg', 'resources/spectrum-icons-color.svg']
];

if (!fs.existsSync(coralDist)) {
  console.error(
    'Coral Spectrum is not installed. Run `npm install` before packaging.'
  );
  process.exit(1);
}

files.forEach(([from, to]) => {
  const source = path.join(coralDist, from);
  const target = path.join(destination, to);

  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.copyFileSync(source, target);
});

const version = require(path.join(
  projectRoot,
  'node_modules',
  '@adobe',
  'coral-spectrum',
  'package.json'
)).version;

fs.writeFileSync(
  path.join(destination, '..', 'README.md'),
  [
    '# Vendored Coral Spectrum',
    '',
    `Copied from \`@adobe/coral-spectrum\` ${version} by \`scripts/vendor-coral.js\`.`,
    'Do not edit these files, and do not commit them: they are regenerated by',
    '`npm install`, `npm run sandbox`, and `npm run package`.',
    ''
  ].join('\n')
);

console.log(
  `Vendored Coral Spectrum ${version} into src/view/vendor/coral (${files.length} files).`
);
